all : context.c context2.c context3.c context_sol.c signal.c
		gcc -w context.c -o context
		gcc -w context2.c -o context2
		gcc -w context3.c -o context3
		gcc -w context_sol.c -o contextSol
		gcc -w signal.c -o signal 

clean :
		rm context context2 context3 contextSol signal

